name: Build

on:
  push:
    branches:
      - '*/*'
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'chore(release)') }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js LTS
        uses: actions/setup-node@v1
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Save build
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: ./dist/ng-base
