name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Set git HEAD
        run: git symbolic-ref HEAD refs/heads/main
      - name: Create release notes
        run: diff --changed-group-format='%>' --unchanged-group-format='' <( git show HEAD~1:CHANGELOG.md ) CHANGELOG.md > RELEASE_NOTES.md || true
      - uses: ncipollo/release-action@v1
        with:
          bodyFile: 'RELEASE_NOTES.md'
          token: ${{ secrets.GITHUB_TOKEN }}
