name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          artifacts: './dist/ng-base'
          bodyFile: 'CHANGELOG.md'
          token: ${{ secrets.GITHUB_TOKEN }}
